<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>

    <TargetFramework>net10.0</TargetFramework>

    <Nullable>enable</Nullable>

    <ImplicitUsings>enable</ImplicitUsings>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <NoWarn>$(NoWarn);1591</NoWarn>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chet.WebApi.Template.Application\Chet.WebApi.Template.Services\Chet.WebApi.Template.Services.csproj" />
    <ProjectReference Include="..\Chet.WebApi.Template.Application\Chet.WebApi.Template.DTOs\Chet.WebApi.Template.DTOs.csproj" />
    <ProjectReference Include="..\Chet.WebApi.Template.Application\Chet.WebApi.Template.Mapping\Chet.WebApi.Template.Mapping.csproj" />
    <ProjectReference Include="..\Chet.WebApi.Template.Infrastructure\Chet.WebApi.Template.Data\Chet.WebApi.Template.Data.csproj" />
    <ProjectReference Include="..\Chet.WebApi.Template.Infrastructure\Chet.WebApi.Template.Caching\Chet.WebApi.Template.Caching.csproj" />
    <ProjectReference Include="..\Chet.WebApi.Template.Infrastructure\Chet.WebApi.Template.Logging\Chet.WebApi.Template.Logging.csproj" />
    <ProjectReference Include="..\Chet.WebApi.Template.Core\Chet.WebApi.Template.Shared\Chet.WebApi.Template.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
  </ItemGroup>

</Project>
