<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.6.122" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Chet.WebApi.Template.Core\Chet.WebApi.Template.Contracts\Chet.WebApi.Template.Contracts.csproj" />
    <ProjectReference Include="..\Chet.WebApi.Template.Configuration\Chet.WebApi.Template.Configuration.csproj" />
  </ItemGroup>

</Project>
